// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwmkYHsY5PG7S1HVjRxUXsd5sbaZRq50',
    appId: '1:132260780222:web:f6e7314fee5fc96e71a6ef',
    messagingSenderId: '132260780222',
    projectId: 'times-curso',
    authDomain: 'times-curso.firebaseapp.com',
    databaseURL: 'https://times-curso-default-rtdb.firebaseio.com',
    storageBucket: 'times-curso.appspot.com',
    measurementId: 'G-EQLJ59D80X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnvkOhaTSsQNpZuj2KMjYqH3t45ZTR0s',
    appId: '1:132260780222:android:b26a15bd54e6c95f71a6ef',
    messagingSenderId: '132260780222',
    projectId: 'times-curso',
    databaseURL: 'https://times-curso-default-rtdb.firebaseio.com',
    storageBucket: 'times-curso.appspot.com',
  );
}
